services:
  - type: web
    name: twittich-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run deploy
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://temporary.com
